# Generated by Django 2.2.13 on 2020-07-29 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('arvestust', '0003_auto_20200729_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('object_id', 'content_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('object_id', 'content_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('object_id', 'content_type', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('object_id', 'content_type', 'content')},
        ),
    ]
