# Generated by Django 2.2.13 on 2020-07-29 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arvestust', '0004_auto_20200729_1701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('object_id', 'user')},
        ),
    ]
