# Generated by Django 2.2.14 on 2020-07-30 19:13

import arvestust.models.abstracts.file
import arvestust.models.validators.file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvestust', '0005_auto_20200729_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage='ekletik.settings.storage.PublicFileStorage', upload_to=arvestust.models.abstracts.file.file_upload_path, validators=[arvestust.models.validators.file.validate_file_size, arvestust.models.validators.file.validate_file_type], verbose_name='file'),
        ),
    ]
