# Generated by Django 2.2.14 on 2020-08-13 01:21

import arvestust.models.abstracts.file
import arvestust.models.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvestust', '0011_auto_20200803_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage='ekletik.settings.storage.PublicFileStorage', upload_to=arvestust.models.abstracts.file.file_upload_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(storage='ekletik.settings.storage.PublicFileStorage', upload_to=arvestust.models.image.file_upload_path, verbose_name='file'),
        ),
    ]
